### ISSUE TITLE
frigate 0.15

### ISSUE THREAD

**Issue by divemasterjm** [kyle4269/frigate_alpr#16]
hi, after installing frigate 0.15 dev, i've got all the time
2024-09-26 12:19:33,351 - __main__ - ERROR - Error getting snapshot: 422

i think they change something about api calling.

**Comment by kyle4269** [comment]
Hey, yeah I noticed that this morning on mine also. Unfortunately I don't have the time to dig into it right now. Hopefully next week I can look and figure it out.

**Comment by divemasterjm** [comment]
Will wait till then, thanks

**Comment by kyle4269** [comment]
Unfortunately I think it's an issue with the new FastAPI they implemented.  Not sure what is going on

**Comment by kyle4269** [comment]
@divemasterjm I've fixed the issue.. Give it a try and let me know.

**Comment by divemasterjm** [comment]
> @divemasterjm I've fixed the issue.. Give it a try and let me know.

testing, i will come to you asap a car is detected.
Thanks

**Comment by divemasterjm** [comment]
> > @divemasterjm I've fixed the issue.. Give it a try and let me know.
> 
> testing, i will come to you asap a car is detected. Thanks

It works!!! Thanks!!
